kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "time-based-scaling.fullname" . }}
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: {{ template "time-based-scaling.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "time-based-scaling.fullname" . }}
