kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: {{ template "time-based-scaling.fullname" . }}
rules:
- apiGroups: ["apps","extensions"]
  resources: ["deployments"]
  verbs: ["get", "list"]
{{ range $i, $schedules := .Values.scaledDeployments -}}
- apiGroups: ["apps","extensions"]
  resources: ["deployments/scale"]
  resourceNames: [{{ .target | quote }}]
  verbs: ["get", "update"]
{{ end -}}
